
import 'bootstrap/dist/css/bootstrap.min.css';
import "./globals.css";
import Header from '@/components/Header'; // ou o caminho correto para o seu componente Header
import { ThemeProvider } from "@/context/ThemeProvider";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>
          <Header/>
          {children}
        </ThemeProvider>
        
      </body>
    </html>
  );
}
